#!/bin/bash
set -eo pipefail
trap "exit" INT

# Pull upstream changes
echo -e "\033[0;32m====>\033[0m Pull origin..."
git pull

echo -e "\033[0;32m====>\033[0m Initial check..."

# Get current release name
CURRENT_RELEASE=$(git tag --sort=committerdate | tail -1)

# Get lastest release name
RELEASE=$(curl --silent "https://api.github.com/repos/Dolibarr/dolibarr/releases/latest" | jq -r ".tag_name")

# Exit script if already up to date
if [ "v${RELEASE}" = $CURRENT_RELEASE ]; then
  echo -e "\033[0;32m=>\033[0m Already up to date..."
  exit 0
fi

# Replace "ARG" line in dockerfile with the new release
sed -i "s#ARG DOLIBARR_VERSION.*#ARG DOLIBARR_VERSION=\"${RELEASE}\"#" Dockerfile

# Replace README link to Dolibarr release
DOLIBARR_BADGE="[![Dolibarr](https://img.shields.io/badge/Dolibarr-${RELEASE}-blue.svg)](https://github.com/Dolibarr/dolibarr/releases/tag/${RELEASE})"
sed -i "s#\[\!\[Dolibarr\].*#${DOLIBARR_BADGE}#" README.md

# Push changes
git add Dockerfile README.md
git commit -m "Update to Dolibarr version v${RELEASE}"
git push origin master

# Create tag
git tag "v${RELEASE}"
git push --tags
